---
- import_playbook: homer-dir.yaml
- name: Deploy Homelab Infrastructure
  hosts: all
  become: yes
  tasks:
    - name: Copy Homer configuration
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../docker/homer/config.yml"
        dest: /mnt/ppppppppds_docker/homer/assets/config.yml
        mode: '0644'
