---
- name: Deploy Homelab Infrastructure
  hosts: all
  become: yes
  tasks:
    - name: Ensure Homer assets directory exists
      ansible.builtin.file:
        path: /mnt/ppppppppds_docker/homer/assets
        state: directory
        mode: '0755'
        recurse: yes
